# Generated by Django 2.1.1 on 2018-09-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorsChampionship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DriversChampionship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='driverschampionship',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Season'),
        ),
        migrations.AddField(
            model_name='constructorschampionship',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Season'),
        ),
        migrations.AddField(
            model_name='constructorschampionship',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
