# Generated by Django 2.1.1 on 2018-10-14 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0004_auto_20181014_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructorschampionshipresult',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_results', to='championship.Season'),
        ),
        migrations.AlterField(
            model_name='driverschampionshipresult',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_results', to='championship.Season'),
        ),
    ]
